### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by Mijobar** [therewillbecode/ten-poker#11]
Windows 10 
Docker version 19.03.8, build afacb8b
Help!

PS C:\Users\DELL-XPS730x\Desktop\ten-poker-master> docker-compose up
Building server
Step 1/8 : FROM fpco/stack-build-small
 ---> 5aab45466769
Step 2/8 : RUN mkdir -p /app
 ---> Using cache
 ---> d464935159cc
Step 3/8 : COPY . /app
 ---> Using cache
 ---> c6b5323f889e
Step 4/8 : WORKDIR /app
 ---> Using cache
 ---> e93007258dd8
Step 5/8 : RUN apt-get update &&   apt-get install libpq-dev lzma-dev libpq-dev -yy
 ---> Using cache
 ---> c5fa874e24ac
Step 6/8 : RUN stack build --only-dependencies
 ---> Running in 7f5d4fb23662
Segmentation fault
**ERROR: Service 'server' failed to build: The command '/bin/sh -c stack build --only-dependencies' returned a non-zero code: 139**
PS C:\Users\DELL-XPS730x\Desktop\ten-poker-master>

**Comment by Mijobar** [comment]
Also tried to compose on Ubuntu and received the same error. Any suggestions? Thanks!

**Comment by LaoTsing** [comment]
can you run stack standalone without docker?

**Comment by therewillbecode** [comment]
Does this bug reproduce for you? @LaoTsing

**Comment by LaoTsing** [comment]
> can you run stack standalone without docker?

no, i as developer needed to customize source code of poker machine)

**Comment by therewillbecode** [comment]
Sorry I am not sure I understand. What do you mean?

**Comment by LaoTsing** [comment]
> Sorry I am not sure I understand. What do you mean?

i mean me need to customize a logic of start game))

**Comment by LaoTsing** [comment]
i sing in, but how to start game??

**Comment by therewillbecode** [comment]
After sign in you get redirected to profile. I thought it would be nice for a player once signed in to see a dashboard like page where they can see stats about their historical games.

**Comment by LaoTsing** [comment]
if you mind, let me join in the development of your project too? can you write a letter to lao.tsing@outlook.com

**Comment by michael-barone** [comment]
> can you run stack standalone without docker?

I am not able to run standalone on Linux. I am getting an error during the "stack build" command

**Comment by LaoTsing** [comment]
but no error on stack build, can you show logs?

**Comment by Mijobar** [comment]
So I was finally able to build it (stack standalone), guess one of the dependencies was unavailable. 

On the client side I am now getting this error.

michael@michael-HP-Pro3500-Series:~/Desktop/ten-poker-master/client$ yarn start
yarn run v1.17.3
$ cross-env NODE_ENV=development node server/index.js
/bin/sh: 1: cross-env: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
michael@michael-HP-Pro3500-Series:~/Desktop/ten-poker-master/client$ sudo yarn start
[sudo] password for michael: 
yarn run v1.17.3
$ cross-env NODE_ENV=development node server/index.js
/bin/sh: 1: cross-env: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
michael@michael-HP-Pro3500-Series:~/Desktop/ten-poker-master/client$ 

Thoughts?

**Comment by LaoTsing** [comment]
oh it is mac os? @therewillbecode there are not tested on mac os?

**Comment by Mijobar** [comment]
@LaoTsing No, this is on ubuntu.

**Comment by LaoTsing** [comment]
i see you started server, only client not working? 

well, i clone project into new folder and in client:
> npm install
> yarn start
and Server started !

**Comment by therewillbecode** [comment]
I haven't tested this on Mac Osx.

If you run `cross-env NODE_ENV=development node server/index.js`

Then you need to have installed cross-env globally. `npm i cross-env -g`

However, the correct way to start the front end is to do.
`npm install && npm start`
or if you are using yarn
`yarn && yarn start`

**Comment by Mijobar** [comment]
after I did npm i cross-env -g i was then able to run. Thanks!
