### ISSUE TITLE
Add bots to game

### ISSUE THREAD

**Issue by LaoTsing** [therewillbecode/ten-poker#13]
Where is a way to add bots?

**Comment by therewillbecode** [comment]
You would need to edit the code base in order to add this feature.

**Comment by LaoTsing** [comment]
and having easy way to add current bots functional?

**Comment by therewillbecode** [comment]
This is something I am currently working on actually. Stay tuned.

**Comment by LaoTsing** [comment]
Also please add creating lobby to API, exactly needed

**Comment by therewillbecode** [comment]
What do you mean by "creating lobby to API"?

**Comment by LaoTsing** [comment]
for peoples, who can create new game, at now is one - Black

**Comment by LaoTsing** [comment]
need api for create new lobby for other friends group :)
