### ISSUE TITLE
disable CORS

### ISSUE THREAD

**Issue by LaoTsing** [therewillbecode/ten-poker#14]
> to XMLHttpRequest at 'http://1fd10247.ngrok.io/profile' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

How to disable CORS check?

**Comment by therewillbecode** [comment]
Try and use a chrome browser extension to disable CORS for your dev environment. Potentially the code should be changed such that CORS is disabled in dev envs.

**Comment by LaoTsing** [comment]
i will publish server on vps and get cors error, client on other vps
